// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Runner.Submissions.Module.Infrastructure.Database;

#nullable disable

namespace Runner.Submissions.Module.Infrastructure.Database.Migrations
{
    [DbContext(typeof(SubmissionsDbContext))]
    partial class SubmissionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("submissions")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CoverageThreshold")
                        .HasColumnType("integer");

                    b.Property<long>("GitLabProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("assignments", "submissions");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.CheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailedTests")
                        .HasColumnType("integer");

                    b.Property<int>("PassedTests")
                        .HasColumnType("integer");

                    b.Property<string>("RawNUnitXml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalTests")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("check_results", "submissions");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "RetryCount");

                    b.ToTable("outbox_messages", "submissions");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("GitLabPipelineId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("submissions", "submissions");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.TestGroupResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CheckResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Failed")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Passed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckResultId");

                    b.ToTable("test_group_results", "submissions");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint");

                    b.Property<string>("GitHubLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("GitHubLogin")
                        .IsUnique();

                    b.ToTable("user_profiles", "submissions");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.CheckResult", b =>
                {
                    b.HasOne("Runner.Submissions.Module.Domain.Entities.Submission", "Submission")
                        .WithOne("CheckResult")
                        .HasForeignKey("Runner.Submissions.Module.Domain.Entities.CheckResult", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.Submission", b =>
                {
                    b.HasOne("Runner.Submissions.Module.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.TestGroupResult", b =>
                {
                    b.HasOne("Runner.Submissions.Module.Domain.Entities.CheckResult", "CheckResult")
                        .WithMany("TestGroupResults")
                        .HasForeignKey("CheckResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckResult");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.CheckResult", b =>
                {
                    b.Navigation("TestGroupResults");
                });

            modelBuilder.Entity("Runner.Submissions.Module.Domain.Entities.Submission", b =>
                {
                    b.Navigation("CheckResult");
                });
#pragma warning restore 612, 618
        }
    }
}
